baseURL = "https://rustymothertruckers.com/"
# baseURL = ""
languageCode = "en"
title = "Rusty Mothertruckers"
theme = "hugo-nederburg-theme"
canonifyurls = false
DefaultContentLanguage = "en"
disqusShortname = "rusty-mothertruckers"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 6

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "\"... its not a swear word in Australia.\""
  description = "The Rusty Mothertruckers" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Graham Weldon"
  authorLink = "https://grahamweldon.com"
  bio = [
    ""
  ]
  copyright = [
    "&copy; 2021 Rusty Mothertruckers",
  ]

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "graham@grahamweldon.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Streams"
  url = "streams/"
  weight = 3

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 4

# this will also be in author bio if there is no writer.
  [params.social]
#   facebook      = "full Social profile url in facebook"
#   googleplus    = "full profile url in googleplus"
#   email         = "email@example.com"
#   twitter       = "full profile url in twitter"
#   linkedin      = "full profile url in linkedin"
#   stackoverflow = "full profile url in stackoverflow"
#   instagram     = "full profile url in instagram"
#   github        = "full profile url in github"
#   pinterest     = "full profile url in pinterest"
#   rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."Graham Weldon"]
    link = "https://grahamweldon.com"
    email = "graham@grahamweldon.com"
    bio = [
      "Graham is a Principle DevOps Engineer professionally, and engages in Game Development as a hobby. He's released <a href='https://store.steampowered.com/app/553610/ArsonVille/' target='_blank'>ArsonVille</a> on Steam!"
    ]
    # facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/predominant"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    github        = "https://github.com/predominant"
    # pinterest     = "full profile url in pinterest"
    twitch        = "https://twitch.tv/grahamweldon"

    [params.writers."Jase"]
    # link = "https://grahamweldon.com"
    email = "rustyjase@gmail.com"
    bio = [
      "Jase is Jase. That's all you need to know."
    ]
    # facebook      = "full lukas profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    # twitter       = "https://twitter.com/predominant"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    # github        = "https://github.com/predominant"
    # pinterest     = "full profile url in pinterest"
    twitch        = "https://twitch.tv/vereoraus"

    [params.writers."Dan Wright"]
    # link = "https://appernetic.io/"
    email = "rustydantrucker@gmail.com"
    bio = [
      "Dan is a digital strategy and project manager for money, and a smartarse as a hobby. He engages in Game Development in moments of poor decision making."
    ]
    # facebook      = "full Göran profile url in facebook"
    # googleplus    = "full profile url in googleplus"
    twitter       = "https://twitter.com/danwofficial"
    # linkedin      = "full profile url in linkedin"
    # stackoverflow = "full profile url in stackoverflow"
    # instagram     = "full profile url in instagram"
    # github        = "full profile url in github"
    # pinterest     = "full profile url in pinterest"